# Generated by Django 3.1.5 on 2021-03-19 16:25

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideosDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_video_id', models.TextField(max_length=15, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField(null=True)),
                ('publish_datetime', models.DateTimeField()),
                ('thumbnail_url', models.URLField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
