# Generated by Django 3.1.5 on 2021-03-19 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('searchApi', '0002_apikeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeys',
            name='last_used',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
