# Generated by Django 3.1.5 on 2021-03-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchApi', '0003_apikeys_last_used'),
        ('searchApi', '0004_auto_20210319_2133'),
    ]

    operations = [
    ]
