# Generated by Django 3.1.5 on 2021-03-19 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchApi', '0006_auto_20210319_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikeys',
            name='is_active',
        ),
    ]
